//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bussines.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Customer = new HashSet<Customer>();
            this.Employee = new HashSet<Employee>();
        }
    
        public int Id { get; set; }
        public int DocTypeId { get; set; }
        public int CityId { get; set; }
        public string DocumentNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DateBird { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string CellphoneNumber { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Customer> Customer { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
