//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVC.ABase.Business.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.UserAccount = new HashSet<UserAccount>();
        }
    
        public int Id { get; set; }
        public int PersonId { get; set; }
        public bool Active { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<UserAccount> UserAccount { get; set; }
    }
}
