//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVC.ABase.Business.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.Module1 = new HashSet<Module>();
            this.ModulesByProfiles = new HashSet<ModulesByProfiles>();
        }
    
        public int Id { get; set; }
        public int ModTypeId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Path { get; set; }
        public bool Active { get; set; }
    
        public virtual ModuleType ModuleType { get; set; }
        public virtual ICollection<Module> Module1 { get; set; }
        public virtual Module Module2 { get; set; }
        public virtual ICollection<ModulesByProfiles> ModulesByProfiles { get; set; }
    }
}
